server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:wise;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    driverClassName: org.h2.Driver

  sql:
    init:
      platform: h2

  mustache:
    check-template-location: false

vaadin:
  launch-browser: true
  pnpm-enabled: true
  whitelisted-packages:
    - com.vaadin
    - org.vaadin
    - dev.hilla
    - com.rodriguezmoreno

logging:
  level:
    org.atmosphere: warn
